--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023.03.17. 8:47:37
-- Server version: 5.5.5-10.4.27-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS todo2;

CREATE DATABASE IF NOT EXISTS todo2
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE todo2;

--
-- Create table `users`
--
CREATE TABLE IF NOT EXISTS users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(50) DEFAULT NULL,
  lastName VARCHAR(50) DEFAULT NULL,
  gender VARCHAR(10) DEFAULT NULL,
  userName VARCHAR(50) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  password VARCHAR(100) DEFAULT NULL,
  number INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 25,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create index `UK_users_email` on table `users`
--
ALTER TABLE users 
  ADD UNIQUE INDEX UK_users_email(email);

--
-- Create index `UK_users_userName` on table `users`
--
ALTER TABLE users 
  ADD UNIQUE INDEX UK_users_userName(userName);

--
-- Create table `todos`
--
CREATE TABLE IF NOT EXISTS todos (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  completed TINYINT(4) DEFAULT 0,
  editing TINYINT(4) DEFAULT 0,
  userId INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE todos 
  ADD CONSTRAINT FK_todos_users_id FOREIGN KEY (userId)
    REFERENCES users(id);

DELIMITER $$

--
-- Create procedure `genTodos`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE genTodos()
BEGIN
DELETE
  FROM todos;

INSERT INTO todos (id, name, completed, userId)
  VALUES (1, "sörözés", 0, 23), (2, "borozás", 0, 23), (3, "pálinkázás", 0, 23),
  (4, "fagyi", 0, 24), (5, "mozi", 0, 24), (6, "szerviz", 0, 24)
;

SELECT
  *
FROM todos;
END
$$

DELIMITER ;

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(23, 'Áron', 'Kis', 'férfi', 'aron', 'kis.aron@gmail.com', '$2b$10$/6Xg/FQygCWI5ax46pfEGund5SkqcHVgzjRjLvTyD/Dl.k2FQ6Zau', 1),
(24, 'Endre', 'Nagy', 'férfi', 'endre', 'nagy.endre@gmail.com', '$2b$10$IVhpMg0XcC1KbG3pTbwkyu9CChhdL6ubWM5FV1K/O3Tsq0NiKBnh2', 1);

-- 
-- Dumping data for table todos
--
INSERT INTO todos VALUES
(1, 'sörözés', 0, 0, 23),
(2, 'borozás', 0, 0, 23),
(3, 'pálinkázás', 0, 0, 23),
(4, 'fagyi', 0, 0, 24),
(5, 'mozi', 0, 0, 24),
(6, 'szerviz', 0, 0, 24);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;